spring:
  profiles:
    active: default,${SPRING_PROFILE:dev}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: ${MAX_UPLOAD_SIZE:8MB}
      max-request-size: ${MAX_REQUEST_SIZE:128MB}
  data:
    redis:
      repositories:
        enabled: false
  datasource:
    hikari:
      auto-commit: false
  thymeleaf:
    enabled: true
    cache: false
    mode: HTML
    encoding: UTF-8

server:
  compression:
    enabled: true
    mime-types:
    - text/html
    - text/xml
    - text/plain
    - text/css
    - text/javascript
    - application/javascript
    - application/json
    - image/svg+xml
    - image/png
    - image/jpeg
    - image/gif
    - image/webp
    - font/ttf
    - font/otf
    - font/woff
    - font/woff2
    - application/x-font-ttf
    - application/x-font-otf
    - application/x-font-woff
    - application/x-font-woff2

logging:
  level:
    web: info
    sql: info
    root: info
