spring:
  jpa:
    open-in-view: false
  devtools:
    livereload.enabled: true
    add-properties: false
  cache:
    jcache:
      config: classpath:ehcache.xml
logging:
  level:
    web: INFO
bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      rate-limits:
        - bandwidths:
            - capacity: 5
              time: 10
              unit: seconds