debug: false

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://127.0.0.1/yomikaze
    username: yomikaze
    password: yomikaze
  jpa:
    hibernate:
      ddl-auto: create
  session:
    store-type: none

logging:
  level:
    web: debug
    sql: debug