spring:
  redis:
    url: ${REDIS_URL}
    client-type: jedis
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  session:
    store-type: redis
    redis:
      flush-mode: immediate
      namespace: yomikaze::session
  cache:
    type: redis
    redis:
      time-to-live: 1h
      key-prefix: yomikaze::cache
logging:
  level:
    web: debug
    sql: info
    root: info