spring:
  redis:
    url: ${REDIS_URL}
    client-type: lettuce
    jedis:
      pool:
        max-active: 10
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  session:
    store-type: redis
    redis:
      flush-mode: immediate
      namespace: yomikaze::session
  cache:
    type: redis
    redis:
      time-to-live: 1h
      key-prefix: yomikaze::cache
  data:
    redis:
      repositories:
        enabled: false
    jpa:
      repositories:
        enabled: true
        bootstrap-mode: default
  thymeleaf:
    enabled: true
    enable-spring-el-compiler: true
    cache: true
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates
    suffix: .html
    servlet:
      content-type: text/html
    template-resolver-order: 1
    check-template-location: true


logging:
  level:
    web: debug
    sql: info
    root: info
